apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-app
  namespace: prod
  labels:
    app: scalable-app
  annotations:
    imageVersion: "build-18" # <-- ADDED: Sets the baseline version
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scalable-app
  template:
    metadata:
      labels:
        app: scalable-app
    spec:
      containers:
      - name: scalable-app
        image: najsv98/scalable-app:build-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: "redis-master.dev.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: FLASK_APP
            value: "app.py"
          - name: FLASK_ENV
            value: "production"
          - name: MONGO_URI
            value: "mongodb://mongos.prod.svc.cluster.local:27017"
          - name: PYTHONUNBUFFERED
            value: "1"